apiVersion: v1
data:
  username: YWRtaW4=
kind: Secret
metadata:
  creationTimestamp: "2020-05-29T03:24:09Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:username: {}
      f:type: {}
    manager: kubectl.exe
    operation: Update
    time: "2020-05-29T03:24:09Z"
  name: mysecret2
  namespace: default
  resourceVersion: "81497"
  selfLink: /api/v1/namespaces/default/secrets/mysecret2
  uid: 450bd269-b403-4f0b-964a-60a25421f194
type: Opaque
