apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  labels:
    app: v1
spec:
  containers:
  - name: nginx
    image: nginx
    resources: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    app: v1
spec:
  containers:
  - name: nginx
    image: nginx
    resources: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx3
  labels:
    app: v1
spec:
  containers:
  - name: nginx
    image: nginx
    resources: {}
