apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    resources: {}
    volumeMounts:
      - name: myvolume
        mountPath: /etc/foo
  volumes:
  - name: myvolume
    secret:
      secretName: mysecret2